apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  template:
    spec:
      serviceAccountName: identity-prod-ksa
      containers:
        - name: identity
          envFrom:
            - configMapRef:
                name: identity-config
            - configMapRef:
                name: identity-prod-env-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: identity-prod-secrets
                  key: DATABASE_URL
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-prod-secrets
                  key: JWT_PRIVATE_KEY
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-prod-secrets
                  key: RESEND_API_KEY
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-prod-secrets
                  key: STORAGE_ACCESS_KEY
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-prod-secrets
                  key: STORAGE_SECRET_KEY
            - name: STORAGE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: identity-prod-secrets
                  key: STORAGE_TOKEN
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: identity-prod-secrets
