apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: identity-prod-secrets
  namespace: identity-prod
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/ethans-services/secrets/identity_prod_database_url/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/ethans-services/secrets/identity_prod_jwt_private_key/versions/latest"
        path: "JWT_PRIVATE_KEY"
      - resourceName: "projects/ethans-services/secrets/identity_prod_resend_api_key/versions/latest"
        path: "RESEND_API_KEY"
      - resourceName: "projects/ethans-services/secrets/identity_prod_storage_access_key/versions/latest"
        path: "STORAGE_ACCESS_KEY"
      - resourceName: "projects/ethans-services/secrets/identity_prod_storage_secret_key/versions/latest"
        path: "STORAGE_SECRET_KEY"
      - resourceName: "projects/ethans-services/secrets/identity_prod_storage_token/versions/latest"
        path: "STORAGE_TOKEN"
  secretObjects:
    - secretName: identity-prod-secrets
      type: Opaque
      data:
        - objectName: "DATABASE_URL"
          key: DATABASE_URL
        - objectName: "JWT_PRIVATE_KEY"
          key: JWT_PRIVATE_KEY
        - objectName: "RESEND_API_KEY"
          key: RESEND_API_KEY
        - objectName: "STORAGE_ACCESS_KEY"
          key: STORAGE_ACCESS_KEY
        - objectName: "STORAGE_SECRET_KEY"
          key: STORAGE_SECRET_KEY
        - objectName: "STORAGE_TOKEN"
          key: STORAGE_TOKEN
