apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-prod-ksa
  namespace: identity-prod
  annotations:
    iam.gke.io/gcp-service-account: identity-prod-sa@ethans-services.iam.gserviceaccount.com
