apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity-staging

resources:
  - ../base
  - namespace.yaml
  - secret-provider-class.yaml
  - configmap-env.yaml

patches:
  - path: deployment-patch.yaml
