apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-staging-ksa
  namespace: identity-staging
  annotations:
    iam.gke.io/gcp-service-account: identity-staging-sa@ethans-services.iam.gserviceaccount.com
