apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: identity=us-central1-docker.pkg.dev/ethans-services/containers/identity
    argocd-image-updater.argoproj.io/identity.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/eswan18/identity
    targetRevision: main
    path: k8s/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: identity-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eswan18/identity
    targetRevision: main
    path: k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: identity-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
