apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: identity-staging
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: identity-staging
      images:
        - alias: identity
          imageName: us-central1-docker.pkg.dev/ethans-services/containers/identity
          commonUpdateSettings:
            updateStrategy: newest-build
